### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by duc03102005** [nizeic/Dodong#16]
** npm start

> dodong@1.0.0 start /home/runner/Dodong-2
> node index.js

/home/runner/Dodong-2/node_modules/youtube-sr/dist/mod.js:374
  throw new Error(`Could not find fetch library. Install "node-fetch"/"undici" or define "fetch" in global scope!`);
  ^

Error: Could not find fetch library. Install "node-fetch"/"undici" or define "fetch" in global scope!
    at getFetch (/home/runner/Dodong-2/node_modules/youtube-sr/dist/mod.js:374:9)
    at Object.<anonymous> (/home/runner/Dodong-2/node_modules/youtube-sr/dist/mod.js:358:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/Dodong-2/node_modules/discord-player/dist/Structures/Queue.js:12:51)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dodong@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dodong@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-17T00_46_32_854Z-debug.log
exit status 1
 **
i got this bug

**Comment by nizeic** [comment]
```
npm install node-fetch@2
```
